---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-abc
  labels:
    name: client-abc
  namespace: client-abc
spec:
  replicas: 2
  selector:
    matchLabels:
      name: client-abc
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: client-abc
    spec:
      containers:
      - image: mmorejon/erase-una-vez-1:0.2.0
        name: erase-una-vez
        env:
        - name: CHARACTER
          value: "la app ABC."
        - name: SLEEP_TIME
          value: "3"
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
          limits:
            memory: "100Mi"
            cpu: "100m"
